import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../../context/AuthContext';

export default function AdminHomeScreen() {
  const { logout } = useAuth();

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <View>
          <Text style={styles.eyebrow}>Admin panel</Text>
          <Text style={styles.title}>Dashboard</Text>
        </View>
        <TouchableOpacity style={styles.logoutButton} onPress={logout}>
          <Ionicons name="log-out-outline" size={18} color="#DC2626" />
        </TouchableOpacity>
      </View>

      <View style={styles.card}>
        <View style={styles.iconBox}>
          <Ionicons name="sparkles-outline" size={22} color="#0C6EFD" />
        </View>
        <Text style={styles.cardTitle}>AI trip plans</Text>
        <Text style={styles.cardText}>
          Destination management has been removed from the active flow. Traveler plans are now generated by Groq and saved inside trips.
        </Text>
      </View>

      <View style={styles.metricRow}>
        <View style={styles.metricCard}>
          <Text style={styles.metricValue}>AI</Text>
          <Text style={styles.metricLabel}>Planning mode</Text>
        </View>
        <View style={styles.metricCard}>
          <Text style={styles.metricValue}>Live</Text>
          <Text style={styles.metricLabel}>Super admin seed</Text>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF', padding: 16, paddingTop: 60 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  eyebrow: { fontSize: 12, color: '#94A3B8', fontFamily: 'Inter' },
  title: { fontSize: 22, color: '#0F172A', fontFamily: 'Inter', fontWeight: '700' },
  logoutButton: { width: 38, height: 38, borderRadius: 10, borderWidth: 1, borderColor: '#E2E8F0', alignItems: 'center', justifyContent: 'center' },
  card: { borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#FFFFFF', borderRadius: 14, padding: 16, marginBottom: 14 },
  iconBox: { width: 40, height: 40, borderRadius: 10, backgroundColor: '#EBF3FF', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  cardTitle: { fontSize: 16, color: '#0F172A', fontFamily: 'Inter', fontWeight: '600', marginBottom: 6 },
  cardText: { fontSize: 13, color: '#475569', fontFamily: 'Inter', lineHeight: 20 },
  metricRow: { flexDirection: 'row', gap: 10 },
  metricCard: { flex: 1, backgroundColor: '#F8FAFC', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, padding: 14 },
  metricValue: { fontSize: 20, color: '#0F172A', fontFamily: 'Inter', fontWeight: '700' },
  metricLabel: { fontSize: 11, color: '#94A3B8', fontFamily: 'Inter', marginTop: 4 },
});
